In [1]:
import gym
import numpy as np

In [2]:
# Load the environment
env = gym.make('FrozenLake-v0')

In [27]:
# Implement Q-table learning algorithm

# Initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])
# Set learning parameters
lr = 0.8
y = 0.95
num_episodes = 2000
# create lists to contain total rewards and steps per episode
rList = []
for i in range(num_episodes):
    # Reset environment and first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j<99:
        j+=1
        
        #Choose an action greedily (with noise) picking from Q table
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n)*(1./(i+1)))
        
        #Get new state and reward from environment
        s1, r, d, _ = env.step(a)
        
        # Update Q-table with new knowledge
        Q[s, a] = Q[s, a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        
        rAll += r
        s = s1
        if d == True:
            break
    
    rList.append(rAll)

In [28]:
print(f'Score over time: {sum(rList)/num_episodes}')

Score over time: 0.544


In [29]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[3.97472204e-01 1.15346801e-02 1.14606321e-02 8.05596325e-03]
 [2.88229440e-03 3.73823903e-04 1.59187291e-03 4.24872384e-01]
 [2.39641965e-03 2.32377429e-03 1.64186824e-03 6.19234550e-02]
 [0.00000000e+00 2.04726330e-04 1.10468476e-03 5.54911851e-02]
 [4.45092173e-01 2.35850152e-03 1.64574784e-03 1.69813047e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.02348641e-03 3.28549749e-07 4.17251758e-04 7.71986242e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.63971822e-04 3.04147185e-03 0.00000000e+00 6.10804576e-01]
 [2.25593591e-03 7.35313445e-01 4.38632019e-03 0.00000000e+00]
 [5.35180199e-02 1.33264248e-03 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.34135961e-03 5.17565877e-03 8.30823545e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.92960784e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.